#!/bin/sh
set -eu
cd `dirname $0`

# Compile `cmpmemhex` and `tester`
mkdir -p bin
gcc -std=c99 cmpmemhex.c -o bin/cmpmemhex || exit
gcc -std=c99 cmpmembin.c -o bin/cmpmembin || exit
make || exit

# Clear the composite logfile
echo "" > ArtlavTestLog.log

# Iterate all test files
for asmfile in Artlav_80186_tests/*.asm; do
	testname=${asmfile#Artlav_80186_tests/}
	testname=${testname%.asm}
	binfile=Artlav_80186_tests/out/${testname}.bin
	dumpfile=Artlav_80186_tests/out/${testname}.dmp
	logfile=Artlav_80186_tests/out/${testname}.log
	mkdir -p $(dirname ${binfile})
	echo $binfile
	# Re-compile the test file (if it's missing or the source is newer)
	if [ ! -f $binfile ] || [ $asmfile -nt $binfile ] ; then
		echo "nasm $asmfile -f bin -o $binfile"
		nasm $asmfile -f bin -o $binfile || exit
	fi
	# Run the test binary
	./bin/tester -b $binfile -O ${dumpfile} --nogui "" --debug-level 2 > ${logfile} || exit
	# Compare the memory dump the exepected memory contents (encoded in leading comments)
	./bin/cmpmemhex $asmfile ${dumpfile} || exit
done
